In [9]:
import pandas as pd
import numpy as np
from datetime import datetime
from datetime import timedelta
from sklearn.linear_model import LogisticRegression

In [10]:
train = pd.read_csv("Fire Data - Train.csv")

In [11]:
train

          Date Acres Burned                      Lat/Long
0   11/16/2018           10        [37.12857, -122.12036]
1   11/15/2018           20         [37.81111, -121.7944]
2   11/14/2018          150  [34.30166667, -119.09916667]
3   11/14/2018           20        [37.61158, -121.94182]
4   11/13/2018          147        [34.18075, -117.43184]
5   11/12/2018           10      [40.888785, -124.001849]
6   11/12/2018          186  [34.26734825, -118.64381589]
7    11/8/2018       96,949          [34.235, -118.70128]
8    11/8/2018         4531        [34.22685, -118.93444]
9    11/8/2018         1500         [38.21396, -121.9424]
10   11/8/2018           35        [39.62194, -123.28774]
11   11/8/2018           88        [39.62194, -123.28774]
12   11/7/2018       153336          [39.8134, -121.4347]
13   11/5/2018           60      [40.346652, -122.308479]
14   11/3/2018           17           [37.0125, -122.046]
15  10/30/2018          550        [39.36529, -121.51707]
16  10/24/2018          120        [36.47766, -119.10433]
17  10/19/2018           58        [35.17693, -120.48861]
18  10/15/2018           10        [39.93427, -121.54103]
19  10/14/2018           38        [40.60866, -122.38366]
20  10/13/2018           12        [40.49618, -122.51597]
21  10/13/2018          167        [36.18401, -120.69955]
22  10/12/2018          160        [38.45673, -121.94658]
23  10/10/2018           15        [41.94046, -122.43933]
24   10/7/2018           63   [37.1769444, -121.68694444]
25   10/7/2018         3889        [40.22027778, -122.18]
26   10/2/2018           32     [36.938674, -119.3127769]
27   10/2/2018          150        [35.97677, -121.24898]
28  12/28/2017           80       [38.869036, -119.61865]
29  12/21/2017           45         [33.9885, -117.38417]
30  12/16/2017           14        [34.71796, -120.27077]
31  12/14/2017           14      [34.605358, -120.414875]
32  12/13/2017           19        [33.88994, -116.91023]
33   12/7/2017          300        [33.59257, -117.14979]
34    12/07/17         4100           [33.3237, -117.163]
35    12/06/17          422        [34.09454, -118.48178]
36   12/5/2017          260        [34.16564, -117.33334]
37   12/5/2017          260        [34.16564, -117.33334]
38   12/5/2017           34        [34.21829, -117.40625]
39    12/05/17         6049        [34.45283, -118.58188]
40    12/05/17        15619        [34.31283, -118.35863]
41    12/04/17       281893        [34.41521, -119.09124]
42   12/4/2017           40         [33.96514, -117.4764]
43  11/29/2017           99      [34.035344, -116.940661]
44    11/25/17           47        [36.38109, -121.00391]
45  11/14/2017           40        [33.90327, -116.50151]
46  11/13/2017          370        [38.46111, -119.48284]
47   11/2/2017           43        [39.81517, -122.28165]
48  10/31/2017           37            [40.774, -122.309]
49  10/26/2017          194        [40.02261, -121.91425]
50  10/26/2017          866        [33.60247, -117.34192]
51  10/26/2017           50        [35.21556, -118.56578]
52  10/24/2017           86        [34.34949, -119.30918]
53  10/24/2017           40         [34.13534, -117.4982]
54  10/23/2017           50         [33.8826, -117.00589]
55  10/21/2017          100        [32.64962, -116.37345]
56  10/20/2017           21        [35.41112, -120.00353]
57  10/18/2017           13        [37.89532, -120.84748]
58  10/17/2017          116         [37.7393, -121.85663]

In [12]:
x_train = train[['Date', 'Lat/Long']]

In [13]:
y_train = train[['Acres Burned']]

In [ ]:
#model
logisticRegr = LogisticRegression()
logisticRegr.fit(x_train, y_train)

In [ ]:
#predict
predictions = logisticRegr.predict(x_test)

In [ ]:
# Use score method to get accuracy of model
score = logisticRegr.score(x_test, y_test)
print(score)